
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'Get started',
  description: 'Generated by create next app',
}

export default function SignupLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
     <main>{children}</main>
    </>
  )
}

